### ISSUE TITLE
pip: error: metadata generation failed

### ISSUE THREAD

**Issue by minsusun** [minsusun/BLARE#1]
pip install -r requirements.txt

```shell
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ls/yts6ydf52dq0fwy1vxxt84dm0000gn/T/pip-install-0rdt6yfl/sentencepiece_db31cde2488b47c78dda9cb03d7fbcec/setup.py", line 29, in <module>
          with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen codecs>", line 918, in open
      FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by minsusun** [comment]
idk why it resolved but installing the latest solved it

verified on M1, python=3.9.19
