### ISSUE TITLE
ModuleNotFoundError: No module named 'tiktoken'

### ISSUE THREAD

**Issue by minsusun** [minsusun/BLARE#3]
```shell
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/FLARE/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/FLARE/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/FLARE/src/openai_api.py", line 17, in <module>
    from .templates import CtxPrompt, ApiReturn, RetrievalInstruction
  File "/home/user/workspace/FLARE/src/templates.py", line 7, in <module>
    import tiktoken
ModuleNotFoundError: No module named 'tiktoken'
```

**Comment by minsusun** [comment]
```shell
pip install tiktoken
```
