### ISSUE TITLE
AttributeError: module 'openai' has no attribute 'error'

### ISSUE THREAD

**Issue by minsusun** [minsusun/BLARE#4]
```shell
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/FLARE/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/FLARE/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/FLARE/src/openai_api.py", line 17, in <module>
    from .templates import CtxPrompt, ApiReturn, RetrievalInstruction
  File "/home/user/workspace/FLARE/src/templates.py", line 8, in <module>
    from .utils import openai_api_call, Utils
  File "/home/user/workspace/FLARE/src/utils.py", line 40, in <module>
    errors_to_catch: tuple = (openai.error.RateLimitError, openai.error.ServiceUnavailableError, openai.error.APIError, openai.error.Timeout, NoKeyAvailable),
AttributeError: module 'openai' has no attribute 'error'
```

**Comment by minsusun** [comment]
```shell
pip install openai==0.28.0
```

use prior version of v1
